spring.application.name=healthTalk

# 데이터베이스 연결 설정
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SQL 스크립트 초기화 설정 (schema.sql 사용)
spring.sql.init.mode=always

# JPA 설정
# Hibernate의 자동 스키마 변경은 끄고, 스키마 일치 여부만 검증
spring.jpa.hibernate.ddl-auto=validate
# 실행되는 SQL 문을 로그로 확인
spring.jpa.show-sql=true
# SQL 로그를 보기 좋게 포맷팅
spring.jpa.properties.hibernate.format_sql=true
# Spring Boot가 자동 감지하므로 생략 가능
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 파일 업로드 사이즈 제한
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 서버 인코딩 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true